/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Affiliate {
  'id' : bigint,
  'link' : string,
  'commission' : bigint,
  'notes' : string,
}
export interface AppSettings {
  'theme' : UITheme,
  'autoSave' : boolean,
  'technical' : string,
  'defaultPlatform' : string,
  'contentPrefs' : ContentPreferences,
}
export interface ContentPreferences {
  'tone' : string,
  'language' : string,
  'style' : string,
}
export type ExternalBlob = Uint8Array;
export interface GenerationParams {
  'url' : string,
  'freeText' : string,
  'audio' : [] | [ExternalBlob],
  'image' : [] | [ExternalBlob],
}
export interface HttpResult {
  'status' : bigint,
  'body' : string,
  'error' : string,
}
export interface Product {
  'id' : bigint,
  'purchasePrice' : bigint,
  'name' : string,
  'tags' : Array<string>,
  'description' : string,
  'specs' : string,
  'salePrice' : bigint,
  'images' : Array<ExternalBlob>,
}
export interface ProductContent {
  'title' : string,
  'purchasePrice' : bigint,
  'tags' : Array<string>,
  'description' : string,
  'specs' : string,
  'salePrice' : bigint,
}
export interface ProductInput {
  'id' : [] | [bigint],
  'purchasePrice' : bigint,
  'name' : string,
  'tags' : Array<string>,
  'description' : string,
  'specs' : string,
  'salePrice' : bigint,
  'images' : Array<ExternalBlob>,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UITheme {
  'accentColor' : string,
  'darkMode' : boolean,
  'fontSize' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addOrUpdateAffiliate' : ActorMethod<[Affiliate], bigint>,
  'addOrUpdateProduct' : ActorMethod<[ProductInput], bigint>,
  'deleteAffiliate' : ActorMethod<[bigint], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'fetchUrl' : ActorMethod<[string], HttpResult>,
  'generateContent' : ActorMethod<[GenerationParams], ProductContent>,
  'getAffiliate' : ActorMethod<[bigint], [] | [Affiliate]>,
  'getAffiliates' : ActorMethod<[], Array<Affiliate>>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getSettings' : ActorMethod<[], [] | [AppSettings]>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateSettings' : ActorMethod<[AppSettings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];