/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Affiliate = IDL.Record({
  'id' : IDL.Nat,
  'link' : IDL.Text,
  'commission' : IDL.Nat,
  'notes' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ProductInput = IDL.Record({
  'id' : IDL.Opt(IDL.Nat),
  'purchasePrice' : IDL.Nat,
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'specs' : IDL.Text,
  'salePrice' : IDL.Nat,
  'images' : IDL.Vec(ExternalBlob),
});
export const HttpResult = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Text,
  'error' : IDL.Text,
});
export const GenerationParams = IDL.Record({
  'url' : IDL.Text,
  'freeText' : IDL.Text,
  'audio' : IDL.Opt(ExternalBlob),
  'image' : IDL.Opt(ExternalBlob),
});
export const ProductContent = IDL.Record({
  'title' : IDL.Text,
  'purchasePrice' : IDL.Nat,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'specs' : IDL.Text,
  'salePrice' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'purchasePrice' : IDL.Nat,
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'specs' : IDL.Text,
  'salePrice' : IDL.Nat,
  'images' : IDL.Vec(ExternalBlob),
});
export const UITheme = IDL.Record({
  'accentColor' : IDL.Text,
  'darkMode' : IDL.Bool,
  'fontSize' : IDL.Nat,
});
export const ContentPreferences = IDL.Record({
  'tone' : IDL.Text,
  'language' : IDL.Text,
  'style' : IDL.Text,
});
export const AppSettings = IDL.Record({
  'theme' : UITheme,
  'autoSave' : IDL.Bool,
  'technical' : IDL.Text,
  'defaultPlatform' : IDL.Text,
  'contentPrefs' : ContentPreferences,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addOrUpdateAffiliate' : IDL.Func([Affiliate], [IDL.Nat], []),
  'addOrUpdateProduct' : IDL.Func([ProductInput], [IDL.Nat], []),
  'deleteAffiliate' : IDL.Func([IDL.Nat], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'fetchUrl' : IDL.Func([IDL.Text], [HttpResult], []),
  'generateContent' : IDL.Func([GenerationParams], [ProductContent], []),
  'getAffiliate' : IDL.Func([IDL.Nat], [IDL.Opt(Affiliate)], ['query']),
  'getAffiliates' : IDL.Func([], [IDL.Vec(Affiliate)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getSettings' : IDL.Func([], [IDL.Opt(AppSettings)], ['query']),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateSettings' : IDL.Func([AppSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Affiliate = IDL.Record({
    'id' : IDL.Nat,
    'link' : IDL.Text,
    'commission' : IDL.Nat,
    'notes' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ProductInput = IDL.Record({
    'id' : IDL.Opt(IDL.Nat),
    'purchasePrice' : IDL.Nat,
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'specs' : IDL.Text,
    'salePrice' : IDL.Nat,
    'images' : IDL.Vec(ExternalBlob),
  });
  const HttpResult = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Text,
    'error' : IDL.Text,
  });
  const GenerationParams = IDL.Record({
    'url' : IDL.Text,
    'freeText' : IDL.Text,
    'audio' : IDL.Opt(ExternalBlob),
    'image' : IDL.Opt(ExternalBlob),
  });
  const ProductContent = IDL.Record({
    'title' : IDL.Text,
    'purchasePrice' : IDL.Nat,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'specs' : IDL.Text,
    'salePrice' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'purchasePrice' : IDL.Nat,
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'specs' : IDL.Text,
    'salePrice' : IDL.Nat,
    'images' : IDL.Vec(ExternalBlob),
  });
  const UITheme = IDL.Record({
    'accentColor' : IDL.Text,
    'darkMode' : IDL.Bool,
    'fontSize' : IDL.Nat,
  });
  const ContentPreferences = IDL.Record({
    'tone' : IDL.Text,
    'language' : IDL.Text,
    'style' : IDL.Text,
  });
  const AppSettings = IDL.Record({
    'theme' : UITheme,
    'autoSave' : IDL.Bool,
    'technical' : IDL.Text,
    'defaultPlatform' : IDL.Text,
    'contentPrefs' : ContentPreferences,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addOrUpdateAffiliate' : IDL.Func([Affiliate], [IDL.Nat], []),
    'addOrUpdateProduct' : IDL.Func([ProductInput], [IDL.Nat], []),
    'deleteAffiliate' : IDL.Func([IDL.Nat], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'fetchUrl' : IDL.Func([IDL.Text], [HttpResult], []),
    'generateContent' : IDL.Func([GenerationParams], [ProductContent], []),
    'getAffiliate' : IDL.Func([IDL.Nat], [IDL.Opt(Affiliate)], ['query']),
    'getAffiliates' : IDL.Func([], [IDL.Vec(Affiliate)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getSettings' : IDL.Func([], [IDL.Opt(AppSettings)], ['query']),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateSettings' : IDL.Func([AppSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };